import 'package:flutter/material.dart';
import '../main.dart';

class AboutNV extends StatefulWidget {
  const AboutNV({super.key});

  @override
  State<AboutNV> createState() => _AboutNVState();
}

class _AboutNVState extends State<AboutNV> {
  var langEng = true;

  @override
  Widget build(BuildContext context) {
    var text = langEng
        ? """
The state of Uttarakhand is known for Himalayan culture and abundant forest wealth. As a symbol of the spiritual, natural and cultural heritage here, 'Nakshatra Vatika' has been established in Raj Bhavan Dehradun.

Since ancient times, the sky has been divided into 360 degrees and if we divide this into 27 parts, then each of its units comes at 13.33 degree (13 degree 20 minutes). Each of these units is called a Nakshatra.

Each Nakshatra is divided equally into 4 Charanas or Padas. These Nakshatras are identified by the position and configuration of the stars in the sky. Akin to the longitude line that expresses the position of a ship moving in the sea, the position of the moving objects (planets) near the Earth is expressed by the Nakshatras.

In Nakshatra Vatika, 27 plants related to these 27 constellations have been planted. This is a unique blend of Indian spirituality, ancient knowledge and nature conservation.

Through these 27 Nakshatras, the position and movements of the nine planets and 12 zodiac signs are assessed in Indian astrology. A plant has also been identified for each planet and zodiac sign. This is the reason there are a total of 51 species of flora at the Vatika. Plants related to 9 planets, 12 zodiac signs and as a symbol of divinity, there are three plants in the names of deities Brahma, Vishnu and Shiva.

The names of the trees related to these Nakshatras, planets and zodiac signs are found in Ayurvedic, mythological, astrological texts. It is further explained that by nurturing the tree of the birth constellation, the individual gains immense prosperity and good health. It is believed that every person should plant a flora, related to his Nakshatra and take care of it.

To further this, tree plantation also provides more oxygen hence positive energy is generated by sitting near these trees. These tree species are rich in secondary metabolites called antioxidants, flavonoids, turpentine and tannins and are widely used in traditional healing systems.

Conservation of these species in the form of Raj Bhavan Nakshatra Vatika is a unique initiative to enrich biodiversity.
        """
        : r"""
आध्यात्मिक, प्राकृतिक और सांस्कृतिक विरासत के प्रतीक के रूप में राजभवन देहरादून में "नक्षत्र वाटिका" की स्थापना की गई है। प्राचीन काल से धरती के ऊपर आकाश को 360 डिग्री में बाँटा गया है। यदि हम 360 डिग्री को 27 भागों में बाँटते हैं तो इसकी प्रत्येक इकाई 13.33 डिग्री (13 डिग्री 20 मिनट) के रूप में आती है। इस प्रत्येक इकाई का एक नक्षत्र बनाया गया है। अब यदि 360 डिग्री को 12 भागों (राशियों) में बांटते हैं तो प्रत्येक राशि चिह्न 30 डिग्री के रूप होता है। जिसे हम 12 अलग-अलग राशियों के नाम से जानते हैं।

प्रत्येक नक्षत्र को 4 चरण या पाद में समान रूप से विभाजित किया जाता है। इन नक्षत्रों की पहचान आसमान के तारों की स्थिति व विन्यास से की जाती है। जिस प्रकार समुद्र में प्रवाह मान जहाज की स्थिति देशांतर रेखा व्यक्त करती है उसी भांति पृथ्वी के निकट भ्रमण पिण्डों (ग्रहों) की स्थिति नक्षत्रों द्वारा व्यक्त की जाती है। नक्षत्र वाटिका में इन्हीं 27 नक्षत्रों से संबन्धित 27 पौधों को स्थान दिया गया है। जो कि भारतीय आध्यात्म, प्राचीन ज्ञान और प्रकृति संरक्षण का अनूठा मिश्रण है।

इन्हीं 27 नक्षत्रों के माध्यम से भारतीय ज्योतिष में नवग्रहों और 12 राशियों की स्थिति और चाल का आंकलन किया जाता है। प्रत्येक ग्रह एवं राशि के लिए भी एक वनस्पति अथवा पौधे की पहचान की गई है। इसीलिये वाटिका में 9 ग्रहों, 12 राशियों से संबधित पौधो तथा त्रिगुणात्मक देव के प्रतीक के रूप में तीन पौधों, कुल 51 पौधों को स्थान दिया गया है। इन नक्षत्रों, ग्रहों तथा राशियों से सम्बन्ध रखने वाले वृक्षों के नाम आयुर्वेदिक, पौराणिक, ज्योतिषीय ग्रन्थों में मिलते है। इन ग्रन्थों में वर्णन है कि जन्म नक्षत्र के वृक्ष की सेवा व वृद्धि करने से मनुष्य का कल्याण होता है।

ऐसा माना जाता है कि प्रत्येक व्यक्ति को उसके नक्षत्र एवं राशि से सम्बन्धित पौधे को लगाकर उसकी देखभाल करनी चाहिए। यह भी माना जाता है कि यह सभी वृक्ष प्रजातियाँ अन्य प्रजातियों की तुलना में अधिक ऑक्सीजन प्रदान करती हैं और इसलिए इन वृक्षों के पास बैठने से सकारात्मक ऊर्जा उत्पन्न होती है। इन वृक्षों की प्रजातियाँ एंटीऑक्सीडेन्ड, फ्लेवोनोइड, तारपीन व टैनिन नामक द्वितीयक चयापचयों (Secondary metabolites) से समृद्ध हैं और इनका प्रयोग पारम्परिक उपचार प्रणालियों में व्यापक रूप से किया जाता है। राजभवन नक्षत्र वाटिका के रूप में इन प्रजातियों के संरक्षण से जैव विविधता को समृद्ध करने की अनुपम पहल है।
""";

    return Scaffold(
        body: Stack(
      fit: StackFit.expand,
      children: [
        Container(
            decoration: const BoxDecoration(
                image: DecorationImage(
                    image: AssetImage('assets/rajBhawan.jpg'),
                    fit: BoxFit.cover))),
        Container(color: mainThemeColor.withOpacity(0.6)),
        AppBar(
          backgroundColor: Colors.transparent,
          elevation: 0,
          iconTheme: const IconThemeData(color: Colors.white),
        ),
        Container(
          margin: EdgeInsets.only(
              left: 20,
              right: 20,
              bottom: 20,
              top: MediaQuery.paddingOf(context).top + kToolbarHeight),
          child: Card(
            child: Padding(
              padding: const EdgeInsets.all(10),
              child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Text(
                      "About Nakshatra Vatika",
                      style: TextStyle(fontSize: 20),
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(
                      height: 25,
                    ),
                    ClipRRect(
                      borderRadius: BorderRadius.circular(8.0),
                      child: Image.asset(
                        'assets/nv.png',
                        fit: BoxFit.contain,
                        height: MediaQuery.of(context).size.height / 2.5,
                      ),
                    ),
                    const SizedBox(
                      height: 25,
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        const Spacer(),
                        TextButton(
                            style: TextButton.styleFrom(
                              backgroundColor: const Color(0xFFFFFFFF),
                            ),
                            child: SizedBox(
                              width:
                                  (MediaQuery.of(context).size.width - 160) /
                                      2,
                              child: const Text(
                                "English",
                                textAlign: TextAlign.center,
                                style: TextStyle(color: Colors.black),
                              ),
                            ),
                            onPressed: () {
                              setState(() {
                                langEng = true;
                              });
                            }),
                        const Spacer(),
                        TextButton(
                            style: TextButton.styleFrom(
                              backgroundColor: const Color(0xFFFFFFFF),
                            ),
                            child: SizedBox(
                              width:
                                  (MediaQuery.of(context).size.width - 160) /
                                      2,
                              child: const Text(
                                r"हिंदी",
                                textAlign: TextAlign.center,
                                style: TextStyle(color: Colors.black),
                              ),
                            ),
                            onPressed: () {
                              setState(() {
                                langEng = false;
                              });
                            }),
                        const Spacer(),
                      ],
                    ),
                    const SizedBox(
                      height: 15,
                    ),
                    Expanded(
                        child: SingleChildScrollView(
                      child: Text(
                        text,
                        textAlign: TextAlign.justify,
                        style: const TextStyle(fontSize: 14),
                      ),
                    ))
                  ]),
            ),
          ),
        )
      ],
    ));
  }
}
